### PR TITLE
Inserted script for mothur users

### PR DESCRIPTION
**Pull request by neavemj**
Hi Meren,

Here is that small script we talked about that changes mothur output into something usable by your scripts. 

Cheers,

Matt.

### CODE REVIEW

**Comment by meren** [comment]
Thank you, Matt!

**Comment by meren** [comment]
I will work on this repository to make it more generic very soon (so multiple demarcation of the same data could easily be prepared for visualization). Thanks for your contribution.

**Comment by neavemj** [comment]
No problem Meren!

If you need any more work done on this or anything else let me know. I'm keen to get involved and try to improve my coding a bit.. :)

Cheers,

Matt.

**Comment by meren** [comment]
Great to hear! I will let you know when I have something that can be played with, then :)

**Pull request merged**
